import random
import string
f = open("user_out.txt", "a")
userNames = []
firstNames = ["james","john","robert","michael","william","david","richard","charles","joseph","thomas","christopher","daniel","paul","mark","donald","george","kenneth","steven","edward","brian","ronald","anthony","kevin","jason","matthew","gary","timothy","jose","larry","jeffrey","frank","scott","eric","stephen","andrew","raymond","gregory","joshua","jerry","dennis","walter","patrick","peter","harold","douglas","henry","carl","arthur","ryan","roger","joe","juan","jack","albert","jonathan","justin","terry","gerald","keith","samuel","willie","ralph","lawrence","nicholas","roy","benjamin","bruce","brandon","adam","harry","fred","wayne","billy","steve","louis","jeremy","aaron","randy","howard","eugene","carlos","russell","bobby","victor","martin","ernest","phillip","todd","jesse","craig","alan","shawn","clarence","sean","philip","chris","johnny","earl","jimmy","antonio","danny","bryan","tony","luis","mike","stanley","leonard","nathan","dale","manuel","rodney","curtis","norman","allen","marvin","vincent","glenn","jeffery","travis","jeff","chad","jacob","lee","melvin","alfred","kyle","francis","bradley","jesus","herbert","frederick","ray","joel","edwin","don","eddie","ricky","troy","randall","barry","alexander","bernard","mario","leroy","francisco","marcus","micheal","theodore","clifford","miguel","oscar","jay","jim","tom","calvin","alex","jon","ronnie","bill","lloyd","tommy","leon","derek","warren","darrell","jerome","floyd","leo","alvin","tim","wesley","gordon","dean","greg","jorge","dustin","pedro","derrick","dan","lewis","zachary","corey","herman","maurice","vernon","roberto","clyde","glen","hector","shane","ricardo","sam","rick","lester","brent","ramon","charlie","tyler","gilbert","gene","amy","anna","sarah","molly","emily","rachel","wendy","irene","sabrina","megan","emma","joanna","katie","kathy","tiffany","holly","leanne","lisa","jenny","jessie","christina","amanda","kelly","nancy","vanessa","veronica","betty","becky","rebecca","zoe","olivia","alice","isabella","erica","stephanie","michelle","lauren","claire","heather","alyssa","melissa","mary","jane","jill","samantha","lucy","mia","sophia","elizabeth","susan","linda","karen","jennifer","anne","jessica","ashley","angela","nicole","laura","diana","doris","maya","elena","aubrey","piper","alexis","alexandra","billie","ariana","nikki","suzanne","marie","connie","debbie","sharon","abby","abigail","grace","hailey","esther","izzy","denise","dana","clara","kathleen","cara","bailey","nellie","madison","maddie","lexi","leah","lacie","jackie","joan","gretchen","penny","patricia","patty","pam","bella","brittney","carrie","elle","ella","julia","kim","courtney","lindsey","natalie","taylor","tina","victoria","allison","eva","katherine","hillary","amber","nina","naomi","gabriella","bianca","natasha","maria","cindy","carol"]
lastNames = ["smith","johnson","williams","jones","brown","davis","miller","wilson","moore","taylor","anderson","thomas","jackson","white","harris","martin","thompson","garcia","martinez","robinson","clark","rodriguez","lewis","lee","walker","hall","allen","young","hernandez","king","wright","lopez","hill","scott","green","adams","baker","gonzalez","nelson","carter","mitchell","perez","roberts","turner","phillips","campbell","parker","evans","edwards","collins","stewart","sanchez","morris","rogers","reed","cook","morgan","bell","murphy","bailey","rivera","cooper","richardson","cox","howard","ward","torres","peterson","gray","ramirez","james","watson","brooks","kelly","sanders","price","bennett","wood","barnes","ross","henderson","coleman","jenkins","perry","powell","long","patterson","hughes","flores","washington","butler","simmons","foster","gonzales","bryant","alexander","russell","griffin","diaz","hayes","gomez","kim","gupta","nichols","tanner","russo","park","chen","zhou","zhang","cho","chang","wang","li","shi","han","jeon","min","yang","satoshi","tanaka","patel","takahashi","noren","tran","nguyen","watkins","franklin","singh","jain","banks","pearson","walters","benson","fitzgerald","michaelson","wolf","garner","goodwin","huang","wu","gu","saunders","ferguson","warren","morello","ruiz","malone","hudson","woods","peters","buckley","fischer"]
for i in range(1000):
    #generates random alphanumeric usernames of size 3
    res = ''.join(random.choices(string.ascii_letters, k=3))
    userNames.append(res)
    # (userID, userName, password, firstName, lastName)

    f.write("(" + str(i) + "," + res + "," + str(i) + "," + firstNames[random.randint(0,100)] + "," + lastNames[random.randint(0,100)] + "),\n")

f.close()
